import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { SCHEMA_VERSION } from "./constants.js";
import type { FileEntry, LineCounts } from "./entry.js";
import {
  buildEntry,
  calcAiRatio,
  countAiRatioEligibleFiles,
  hasGeneratedArtifactMarkers,
  isGeneratedArtifactPath,
} from "./entry.js";

describe("isGeneratedArtifactPath", () => {
  it("detects known generated artifact paths", () => {
    assert.equal(isGeneratedArtifactPath("website/.next/server/app.js"), true);
    assert.equal(isGeneratedArtifactPath("ios/Runner/GeneratedPluginRegistrant.swift"), true);
    assert.equal(isGeneratedArtifactPath("lib/src/model.freezed.dart"), true);
    assert.equal(isGeneratedArtifactPath("proto/service.pb.go"), true);
    assert.equal(isGeneratedArtifactPath("schema/user.generated.ts"), true);
    assert.equal(isGeneratedArtifactPath("src/bindings.generated.rs"), true);
    assert.equal(isGeneratedArtifactPath("src/generated.ts"), false);
  });

  it("does not treat generic directory names as generated by themselves", () => {
    assert.equal(isGeneratedArtifactPath("build/service.ts"), false);
    assert.equal(isGeneratedArtifactPath("target/app.rs"), false);
    assert.equal(isGeneratedArtifactPath("gen/client.ts"), false);
    assert.equal(isGeneratedArtifactPath("generated/source.ts"), false);
    assert.equal(isGeneratedArtifactPath("packages/pr-report/dist/index.js"), false);
  });
});

describe("hasGeneratedArtifactMarkers", () => {
  it("detects common generated headers across languages", () => {
    assert.equal(
      hasGeneratedArtifactMarkers(
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
      ),
      true,
    );
    assert.equal(
      hasGeneratedArtifactMarkers(
        "// Generated by SwiftGen — https://github.com/SwiftGen/SwiftGen\n",
      ),
      true,
    );
    assert.equal(
      hasGeneratedArtifactMarkers(
        "/* automatically generated by rust-bindgen 0.71.1 */\npub const FOO: i32 = 1;\n",
      ),
      true,
    );
    assert.equal(hasGeneratedArtifactMarkers("export const generated = false;\n"), false);
  });
});

describe("calcAiRatio", () => {
  it("uses line counts when totalAddedLines > 0", () => {
    const files: FileEntry[] = [
      { path: "a.ts", by_ai: true },
      { path: "b.ts", by_ai: false },
    ];
    const lineCounts: LineCounts = { aiAddedLines: 30, totalAddedLines: 100, deletedLines: 5 };
    assert.equal(calcAiRatio(files, lineCounts), 30);
  });

  it("falls back to file ratio when lineCounts is undefined", () => {
    const files: FileEntry[] = [
      { path: "a.ts", by_ai: true },
      { path: "b.ts", by_ai: true },
      { path: "c.ts", by_ai: false },
    ];
    assert.equal(calcAiRatio(files), 67);
  });

  it("returns 0 when files is empty", () => {
    assert.equal(calcAiRatio([]), 0);
  });

  it("falls back to file ratio when totalAddedLines is 0", () => {
    const files: FileEntry[] = [
      { path: "a.ts", by_ai: true },
      { path: "b.ts", by_ai: false },
    ];
    const lineCounts: LineCounts = { aiAddedLines: 0, totalAddedLines: 0, deletedLines: 3 };
    // totalAddedLines=0 → file ratio: 1/2 = 50%
    assert.equal(calcAiRatio(files, lineCounts), 50);
  });

  it("returns 100 when all files are AI-authored", () => {
    const files: FileEntry[] = [{ path: "a.ts", by_ai: true }];
    assert.equal(calcAiRatio(files), 100);
  });

  it("returns 0 when no files are AI-authored", () => {
    const files: FileEntry[] = [
      { path: "a.ts", by_ai: false },
      { path: "b.ts", by_ai: false },
    ];
    assert.equal(calcAiRatio(files), 0);
  });

  it("excludes generated artifacts from file-level ratio", () => {
    const files: FileEntry[] = [
      { path: "packages/pr-report/src/index.ts", by_ai: true },
      { path: "packages/pr-report/src/index.generated.ts", by_ai: false },
    ];
    assert.equal(calcAiRatio(files), 100);
  });
});

describe("countAiRatioEligibleFiles", () => {
  it("counts only non-generated files", () => {
    const files: FileEntry[] = [
      { path: "src/a.ts", by_ai: true },
      { path: "src/index.generated.ts", by_ai: false },
      { path: "lib/src/model.freezed.dart", by_ai: false },
      { path: "src/b.ts", by_ai: false },
    ];
    assert.deepEqual(countAiRatioEligibleFiles(files), { total: 2, ai: 1 });
  });

  it("respects explicit generated flags from recorded notes", () => {
    const files: FileEntry[] = [
      { path: "Generated.swift", by_ai: false, generated: true },
      { path: "Sources/App.swift", by_ai: true },
    ];
    assert.deepEqual(countAiRatioEligibleFiles(files), { total: 1, ai: 1 });
  });
});

describe("buildEntry", () => {
  const sessionId = "a0000000-0000-4000-8000-000000000001";

  it("builds a basic entry with correct schema version", () => {
    const entry = buildEntry({
      agent: "claude",
      sessionId,
      model: "claude-3-opus",
      interactions: [{ prompt: "write a function", response: "here it is" }],
      commitFiles: ["src/foo.ts"],
      aiFiles: ["src/foo.ts"],
    });
    assert.equal(entry.v, SCHEMA_VERSION);
    assert.equal(entry.session_id, sessionId);
    assert.equal(entry.agent, "claude");
    assert.equal(entry.model, "claude-3-opus");
    assert.equal(typeof entry.timestamp, "string");
    assert.ok(!Number.isNaN(Date.parse(entry.timestamp)));
  });

  it("sets method=line and attaches lines when lineCounts provided", () => {
    const lineCounts: LineCounts = { aiAddedLines: 50, totalAddedLines: 100, deletedLines: 10 };
    const entry = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r" }],
      commitFiles: ["a.ts"],
      aiFiles: ["a.ts"],
      lineCounts,
    });
    assert.equal(entry.attribution.method, "line");
    assert.equal(entry.attribution.ai_ratio, 50);
    assert.deepEqual(entry.attribution.lines, {
      ai_added: 50,
      total_added: 100,
      deleted: 10,
    });
  });

  it("sets method=file when lineCounts is undefined", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r" }],
      commitFiles: ["a.ts", "b.ts"],
      aiFiles: ["a.ts"],
    });
    assert.equal(entry.attribution.method, "file");
    assert.equal(entry.attribution.ai_ratio, 50);
    assert.equal(entry.attribution.lines, undefined);
  });

  it("sets method=none and ai_ratio=0 when totalAddedLines is 0", () => {
    const lineCounts: LineCounts = { aiAddedLines: 0, totalAddedLines: 0, deletedLines: 5 };
    const entry = buildEntry({
      sessionId,
      interactions: [],
      commitFiles: ["a.ts"],
      aiFiles: ["a.ts"],
      lineCounts,
    });
    assert.equal(entry.attribution.method, "none");
    assert.equal(entry.attribution.ai_ratio, 0);
  });

  it("attaches tools from interactionTools map", () => {
    const interactionTools = new Map<number, string[] | null>([
      [0, ["Edit", "Write"]],
      [1, null],
    ]);
    const entry = buildEntry({
      sessionId,
      interactions: [
        { prompt: "p1", response: "r1" },
        { prompt: "p2", response: "r2" },
      ],
      commitFiles: [],
      aiFiles: [],
      interactionTools,
    });
    assert.deepEqual(entry.interactions[0].tools, ["Edit", "Write"]);
    assert.equal(entry.interactions[1].tools, null);
  });

  it("defaults agent and model to null when not provided", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [],
      commitFiles: [],
      aiFiles: [],
    });
    assert.equal(entry.agent, null);
    assert.equal(entry.model, null);
  });

  it("builds files array with correct by_ai flags", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [],
      commitFiles: ["a.ts", "b.ts", "c.ts"],
      aiFiles: ["a.ts", "c.ts"],
    });
    assert.deepEqual(entry.files, [
      { path: "a.ts", by_ai: true },
      { path: "b.ts", by_ai: false },
      { path: "c.ts", by_ai: true },
    ]);
  });

  it("marks generated files when provided", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [],
      commitFiles: ["Sources/App.swift", "Generated.swift"],
      aiFiles: ["Sources/App.swift"],
      generatedFiles: ["Generated.swift"],
    });
    assert.deepEqual(entry.files, [
      { path: "Sources/App.swift", by_ai: true },
      { path: "Generated.swift", by_ai: false, generated: true },
    ]);
  });

  it("inherits tools from interaction when interactionTools has no entry for that index", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r", tools: ["Bash"] }],
      commitFiles: [],
      aiFiles: [],
    });
    assert.deepEqual(entry.interactions[0].tools, ["Bash"]);
  });

  it("preserves interaction context when provided", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r", context: "previous response context" }],
      commitFiles: [],
      aiFiles: [],
    });
    assert.equal(entry.interactions[0].context, "previous response context");
  });

  it("omits blank interaction context", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r", context: "   " }],
      commitFiles: [],
      aiFiles: [],
    });
    assert.equal(entry.interactions[0].context, undefined);
  });

  it("does not change attribution when interaction context is present", () => {
    const base = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r" }],
      commitFiles: ["a.ts", "b.ts"],
      aiFiles: ["a.ts"],
    });
    const withContext = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r", context: "why this prompt matters" }],
      commitFiles: ["a.ts", "b.ts"],
      aiFiles: ["a.ts"],
    });

    assert.deepEqual(withContext.attribution, base.attribution);
    assert.deepEqual(withContext.files, base.files);
  });

  it("omits files_touched when empty", () => {
    const entry = buildEntry({
      sessionId,
      interactions: [{ prompt: "p", response: "r", files_touched: [] }],
      commitFiles: [],
      aiFiles: [],
    });
    assert.equal(entry.interactions[0].files_touched, undefined);
  });
});
