import { SCHEMA_VERSION } from "./constants.js";

// ─── Interfaces ───

export interface FileEntry {
  path: string;
  by_ai: boolean;
  generated?: boolean;
}

export interface AttributionLines {
  ai_added: number;
  total_added: number;
  deleted: number;
}

export interface Attribution {
  ai_ratio: number;
  method: "line" | "file" | "none";
  lines?: AttributionLines;
}

export interface InteractionContext {
  kind: "reference" | "scope";
  source: "previous_response" | "current_response";
  text: string;
}

export type PromptSelectionSignal =
  | "primary_edit_turn"
  | "exact_commit_path"
  | "commit_file_basename"
  | "diff_identifier"
  | "response_exact_commit_path"
  | "response_basename_or_identifier"
  | "commit_subject_overlap"
  | "list_or_checklist_shape"
  | "multi_line_instruction"
  | "inline_code_or_path_shape"
  | "substantive_prompt_shape"
  | "before_commit_boundary"
  | "between_non_excluded_prompts";

export interface InteractionSelection {
  schema: 1;
  source: "primary" | "window" | "tail" | "fallback";
  signals: PromptSelectionSignal[];
}

export interface Interaction {
  prompt: string;
  response: string | null;
  context?: string;
  contexts?: InteractionContext[];
  files_touched?: string[];
  line_stats?: Record<string, { added: number; deleted: number }>;
  tools?: string[] | null;
  selection?: InteractionSelection;
}

export type PromptSelectionRole =
  | "primary"
  | "direct_anchor"
  | "scope"
  | "tail"
  | "anchored_bridge"
  | "bridge"
  | "background";

export type PromptRuntimeLevel = "low" | "medium" | "high";

export type PromptRuntimeSelection = {
  score: number;
  role: PromptSelectionRole;
  level: PromptRuntimeLevel;
};

export type PromptDetail = "compact" | "standard" | "full";

export const DEFAULT_PROMPT_DETAIL: PromptDetail = "standard";

export interface AgentnoteEntry {
  v: number;
  agent?: string | null;
  session_id: string;
  timestamp: string;
  model?: string | null;
  interactions: Interaction[];
  files: FileEntry[];
  attribution: Attribution;
}

// ─── Internal types ───

export interface LineCounts {
  aiAddedLines: number;
  totalAddedLines: number;
  deletedLines: number;
}

// Best-effort generated-artifact heuristics grouped by ecosystem so each rule
// stays explainable when we broaden support across languages and frameworks.
const GENERATED_DIR_SEGMENTS = new Set([
  // Web / JS / TS build outputs
  ".next",
  ".nuxt",
  "coverage",
  // Monorepo / remote-cache build outputs
  ".turbo",
  ".yarn",
  "bazel-bin",
  "bazel-out",
  "bazel-testlogs",
  // Mobile / Flutter build caches
  ".dart_tool",
  "DerivedData",
]);
const GENERATED_FILE_NAMES = new Set([
  // Flutter tool-managed dependency snapshot
  ".flutter-plugins-dependencies",
  // Flutter desktop / mobile plugin registrants
  "generated_plugin_registrant.dart",
  "GeneratedPluginRegistrant.java",
  "GeneratedPluginRegistrant.swift",
  "GeneratedPluginRegistrant.m",
  "GeneratedPluginRegistrant.h",
]);
const GENERATED_FILE_SUFFIXES = [
  // Web / TS / GraphQL / OpenAPI codegen
  ".gen.ts",
  ".gen.tsx",
  ".generated.js",
  ".generated.jsx",
  ".generated.ts",
  ".generated.tsx",
  // Dart / Flutter codegen
  ".chopper.dart",
  ".config.dart",
  ".freezed.dart",
  ".g.dart",
  ".gr.dart",
  ".mocks.dart",
  ".pb.dart",
  ".pbjson.dart",
  ".pbenum.dart",
  ".pbserver.dart",
  // Go codegen
  ".pb.go",
  ".pb.gw.go",
  ".twirp.go",
  ".gen.go",
  ".generated.go",
  "_gen.go",
  "_generated.go",
  "_string.go",
  // Rust codegen
  ".generated.rs",
  ".pb.rs",
  "_generated.rs",
  // Kotlin / Swift codegen
  ".g.kt",
  ".gen.kt",
  ".generated.kt",
  ".g.swift",
  ".generated.swift",
  // Web sourcemaps
  ".map",
];
const GENERATED_CONTENT_PATTERNS = [
  // Cross-language generator banners used by protoc, sqlc, stringer, bindgen, etc.
  /\bcode generated\b[\s\S]{0,160}\bdo not edit\b/i,
  /\bautomatically generated by\b/i,
  /\bthis file was generated by\b/i,
  // Annotation-style banners commonly used in Java / Kotlin / JS ecosystems.
  /\B@generated\b/i,
  // Named generators across Web, mobile, backend, and protobuf toolchains.
  /\bgenerated by (?:swiftgen|sourcery|protoc|buf|sqlc|openapi(?:-generator)?|openapitools|wire|freezed|build_runner|mockgen|rust-bindgen|apollo|drift|flutterfire|ksp)\b/i,
];

export function isGeneratedArtifactPath(path: string): boolean {
  const normalized = path.replaceAll("\\", "/");
  const segments = normalized.split("/").filter(Boolean);
  if (segments.some((segment) => GENERATED_DIR_SEGMENTS.has(segment))) {
    return true;
  }

  const basename = segments.at(-1) ?? normalized;
  if (GENERATED_FILE_NAMES.has(basename)) return true;
  return GENERATED_FILE_SUFFIXES.some((suffix) => basename.endsWith(suffix));
}

export function hasGeneratedArtifactMarkers(content: string): boolean {
  const header = content.slice(0, 2048).toLowerCase();
  return GENERATED_CONTENT_PATTERNS.some((pattern) => pattern.test(header));
}

export function filterAiRatioEligibleFiles(files: FileEntry[]): FileEntry[] {
  return files.filter((file) => !file.generated && !isGeneratedArtifactPath(file.path));
}

export function countAiRatioEligibleFiles(files: FileEntry[]): { total: number; ai: number } {
  const eligible = filterAiRatioEligibleFiles(files);
  return {
    total: eligible.length,
    ai: eligible.filter((file) => file.by_ai).length,
  };
}

export function normalizeInteractionContexts(interaction: {
  context?: string;
  contexts?: InteractionContext[];
}): InteractionContext[] {
  const normalized: InteractionContext[] = [];
  const seen = new Set<string>();

  const add = (context: InteractionContext | undefined) => {
    const text = context?.text.trim();
    if (!context || !text) return;
    const key = text;
    if (seen.has(key)) return;
    seen.add(key);
    normalized.push({ kind: context.kind, source: context.source, text });
  };

  const legacy = interaction.context?.trim();
  if (legacy) {
    add({ kind: "reference", source: "previous_response", text: legacy });
  }

  for (const context of interaction.contexts ?? []) {
    add(context);
  }

  return normalized;
}

export function parsePromptDetail(value: string | null | undefined): PromptDetail {
  const normalized = (value ?? "").trim().toLowerCase();
  if (!normalized) return DEFAULT_PROMPT_DETAIL;
  if (normalized === "compact" || normalized === "standard" || normalized === "full") {
    return normalized;
  }
  throw new Error("prompt_detail must be one of: compact, standard, full");
}

export function shouldRenderInteractionByPromptDetail(
  interaction: Pick<Interaction, "prompt" | "selection">,
  detail: PromptDetail,
): boolean {
  const runtime = resolvePromptRuntimeSelection(interaction.selection, interaction);
  if (detail === "full") return true;
  if (detail === "standard") return runtime.level !== "low";
  return runtime.level === "high";
}

export function resolvePromptRuntimeSelection(
  selection: InteractionSelection | undefined,
  interaction: Pick<Interaction, "prompt">,
): PromptRuntimeSelection {
  if (!selection) return { score: 100, role: "primary", level: "high" };
  const signals = runtimePromptSelectionSignals(selection.signals, interaction.prompt);
  const role = resolvePromptRuntimeRole(selection.source, signals, interaction.prompt);
  const score = scorePromptRuntime({ role, signals });
  return { score, role, level: resolvePromptRuntimeLevel({ score, role }) };
}

export function resolvePromptRuntimeRole(
  source: InteractionSelection["source"],
  signals: PromptSelectionSignal[],
  prompt: string,
): PromptSelectionRole {
  if (source === "primary" || signals.includes("primary_edit_turn")) return "primary";
  if (signals.includes("exact_commit_path") || signals.includes("diff_identifier")) {
    return "direct_anchor";
  }
  if (isShortSelectionPrompt(prompt) && hasBridgeAnchorSignal(signals)) {
    return "anchored_bridge";
  }
  if (hasScopeSignal(signals)) return "scope";
  if (source === "tail") return "tail";
  if (isShortSelectionPrompt(prompt) && signals.includes("between_non_excluded_prompts")) {
    return "bridge";
  }
  return "background";
}

export function scorePromptRuntime(opts: {
  role: PromptSelectionRole;
  signals: PromptSelectionSignal[];
}): number {
  let score = roleBaseScore(opts.role);
  for (const signal of opts.signals) score += signalScore(signal);
  const [min, max] = roleScoreClamp(opts.role);
  score = Math.max(min, Math.min(score, max));
  if (opts.role === "primary") return Math.max(score, 80);
  if (opts.role === "bridge") {
    const maxBridgeScore = opts.signals.includes("substantive_prompt_shape") ? 55 : 44;
    return Math.min(score, maxBridgeScore);
  }
  if (opts.role === "anchored_bridge") return Math.min(score, 65);
  if (opts.role === "tail" && !hasTailStructuralAnchorSignal(opts.signals)) {
    return Math.min(score, 44);
  }
  return score;
}

export function resolvePromptRuntimeLevel(runtime: {
  score: number;
  role: PromptSelectionRole;
}): PromptRuntimeLevel {
  if (runtime.role === "primary") return "high";
  if (runtime.role === "bridge") return runtime.score >= 45 ? "medium" : "low";
  if (runtime.role === "anchored_bridge") return runtime.score >= 45 ? "medium" : "low";
  if (runtime.score >= 75) return "high";
  if (runtime.score >= 45) return "medium";
  return "low";
}

function roleBaseScore(role: PromptSelectionRole): number {
  switch (role) {
    case "primary":
      return 90;
    case "direct_anchor":
      return 75;
    case "scope":
      return 60;
    case "tail":
    case "anchored_bridge":
      return 45;
    case "bridge":
      return 25;
    case "background":
      return 15;
  }
}

function roleScoreClamp(role: PromptSelectionRole): [number, number] {
  switch (role) {
    case "primary":
      return [80, 100];
    case "direct_anchor":
      return [65, 95];
    case "scope":
      return [50, 80];
    case "tail":
      return [35, 70];
    case "anchored_bridge":
      return [40, 65];
    case "bridge":
      return [20, 55];
    case "background":
      return [0, 30];
  }
}

function signalScore(signal: PromptSelectionSignal): number {
  switch (signal) {
    case "primary_edit_turn":
      return 0;
    case "exact_commit_path":
      return 30;
    case "commit_file_basename":
      return 10;
    case "diff_identifier":
      return 20;
    case "response_exact_commit_path":
      return 18;
    case "response_basename_or_identifier":
      return 10;
    case "commit_subject_overlap":
      return 4;
    case "list_or_checklist_shape":
      return 10;
    case "multi_line_instruction":
      return 6;
    case "inline_code_or_path_shape":
      return 6;
    case "substantive_prompt_shape":
      return 12;
    case "before_commit_boundary":
      return 5;
    case "between_non_excluded_prompts":
      return 8;
  }
}

function hasBridgeAnchorSignal(signals: PromptSelectionSignal[]): boolean {
  return (
    signals.includes("exact_commit_path") ||
    signals.includes("diff_identifier") ||
    signals.includes("commit_file_basename")
  );
}

function hasTailStructuralAnchorSignal(signals: PromptSelectionSignal[]): boolean {
  return (
    signals.includes("exact_commit_path") ||
    signals.includes("diff_identifier") ||
    signals.includes("commit_file_basename") ||
    signals.includes("inline_code_or_path_shape") ||
    signals.includes("substantive_prompt_shape")
  );
}

function hasScopeSignal(signals: PromptSelectionSignal[]): boolean {
  return signals.includes("list_or_checklist_shape") || signals.includes("multi_line_instruction");
}

export function isShortSelectionPrompt(prompt: string): boolean {
  const trimmed = prompt.trim();
  if (!trimmed) return true;
  return trimmed.length <= 120 && trimmed.split(/\s+/).length <= 12;
}

export function hasSubstantivePromptShape(text: string): boolean {
  const trimmed = text.trim();
  const compact = trimmed.replace(/\s+/g, "");
  if (!compact) return false;
  const wordTokens = text.match(/[\p{L}\p{N}_-]+/gu) ?? [];
  const hasCjkOrHangul =
    /[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}]/u.test(trimmed);
  if (wordTokens.length >= 7) return true;
  if (wordTokens.length >= 4 && (/[?？]/.test(trimmed) || hasCjkOrHangul)) return true;
  return hasCjkOrHangul && [...compact].length >= 12;
}

function runtimePromptSelectionSignals(
  signals: PromptSelectionSignal[],
  prompt: string,
): PromptSelectionSignal[] {
  if (signals.includes("substantive_prompt_shape") || !hasSubstantivePromptShape(prompt)) {
    return signals;
  }
  return [...signals, "substantive_prompt_shape"];
}

// ─── Functions ───

/**
 * Calculate AI ratio.
 * When line counts are available, uses line-level ratio (added lines only).
 * Falls back to file-count ratio when blob data is unavailable.
 */
export function calcAiRatio(files: FileEntry[], lineCounts?: LineCounts): number {
  if (lineCounts && lineCounts.totalAddedLines > 0) {
    return Math.round((lineCounts.aiAddedLines / lineCounts.totalAddedLines) * 100);
  }
  const eligible = countAiRatioEligibleFiles(files);
  if (eligible.total === 0) return 0;
  return Math.round((eligible.ai / eligible.total) * 100);
}

/** Determine attribution method from available data. */
function resolveMethod(lineCounts?: LineCounts): "line" | "file" | "none" {
  if (!lineCounts) return "file";
  if (lineCounts.totalAddedLines === 0) return "none";
  return "line";
}

/** Build an agentnote entry from collected data. */
export function buildEntry(opts: {
  agent?: string | null;
  sessionId: string;
  model?: string | null;
  interactions: Interaction[];
  commitFiles: string[];
  aiFiles: string[];
  generatedFiles?: string[];
  lineCounts?: LineCounts;
  /** Per-interaction tools, keyed by interaction index. null = no data. */
  interactionTools?: Map<number, string[] | null>;
}): AgentnoteEntry {
  const generatedFiles = new Set(opts.generatedFiles ?? []);
  const files: FileEntry[] = opts.commitFiles.map((path) => ({
    path,
    by_ai: opts.aiFiles.includes(path),
    ...(generatedFiles.has(path) ? { generated: true } : {}),
  }));

  const method = resolveMethod(opts.lineCounts);
  const aiRatio = method === "none" ? 0 : calcAiRatio(files, opts.lineCounts);

  const attribution: Attribution = { ai_ratio: aiRatio, method };
  if (opts.lineCounts) {
    attribution.lines = {
      ai_added: opts.lineCounts.aiAddedLines,
      total_added: opts.lineCounts.totalAddedLines,
      deleted: opts.lineCounts.deletedLines,
    };
  }

  const interactions = opts.interactions.map((i, idx) => {
    const base: Interaction = { prompt: i.prompt, response: i.response };
    const contexts = normalizeInteractionContexts(i);
    if (contexts.length > 0) {
      base.contexts = contexts;
    }
    if (i.files_touched && i.files_touched.length > 0) {
      base.files_touched = i.files_touched;
    }
    if (i.selection) {
      base.selection = {
        schema: i.selection.schema,
        source: i.selection.source,
        signals: [...i.selection.signals],
      };
    }
    // Attach tools from interactionTools map (preserving null), or inherit from interaction.
    if (opts.interactionTools?.has(idx)) {
      base.tools = opts.interactionTools.get(idx) ?? null;
    } else if (i.tools !== undefined) {
      base.tools = i.tools;
    }
    return base;
  });

  return {
    v: SCHEMA_VERSION,
    agent: opts.agent ?? null,
    session_id: opts.sessionId,
    timestamp: new Date().toISOString(),
    model: opts.model ?? null,
    interactions,
    files,
    attribution,
  };
}
