import { SCHEMA_VERSION } from "./constants.js";

// ─── Interfaces ───

export interface FileEntry {
  path: string;
  by_ai: boolean;
  generated?: boolean;
}

export interface AttributionLines {
  ai_added: number;
  total_added: number;
  deleted: number;
}

export interface Attribution {
  ai_ratio: number;
  method: "line" | "file" | "none";
  lines?: AttributionLines;
}

export interface Interaction {
  prompt: string;
  response: string | null;
  files_touched?: string[];
  line_stats?: Record<string, { added: number; deleted: number }>;
  tools?: string[] | null;
}

export interface AgentnoteEntry {
  v: number;
  agent?: string | null;
  session_id: string;
  timestamp: string;
  model?: string | null;
  interactions: Interaction[];
  files: FileEntry[];
  attribution: Attribution;
}

// ─── Internal types ───

export interface LineCounts {
  aiAddedLines: number;
  totalAddedLines: number;
  deletedLines: number;
}

// Best-effort generated-artifact heuristics grouped by ecosystem so each rule
// stays explainable when we broaden support across languages and frameworks.
const GENERATED_DIR_SEGMENTS = new Set([
  // Web / JS / TS build outputs
  ".next",
  ".nuxt",
  "coverage",
  "dist",
  "out",
  // Monorepo / remote-cache build outputs
  ".turbo",
  ".yarn",
  "bazel-bin",
  "bazel-out",
  "bazel-testlogs",
  // Mobile / Flutter build caches
  ".dart_tool",
  "DerivedData",
  // Multi-language generic build directories (Android, Kotlin, Rust, Go, Dart)
  "build",
  "gen",
  "generated",
  "target",
]);
const GENERATED_FILE_NAMES = new Set([
  // Flutter tool-managed dependency snapshot
  ".flutter-plugins-dependencies",
  // Flutter desktop / mobile plugin registrants
  "generated_plugin_registrant.dart",
  "GeneratedPluginRegistrant.java",
  "GeneratedPluginRegistrant.swift",
  "GeneratedPluginRegistrant.m",
  "GeneratedPluginRegistrant.h",
]);
const GENERATED_FILE_SUFFIXES = [
  // Web / TS / GraphQL / OpenAPI codegen
  ".gen.ts",
  ".gen.tsx",
  ".generated.js",
  ".generated.jsx",
  ".generated.ts",
  ".generated.tsx",
  // Dart / Flutter codegen
  ".chopper.dart",
  ".config.dart",
  ".freezed.dart",
  ".g.dart",
  ".gr.dart",
  ".mocks.dart",
  ".pb.dart",
  ".pbjson.dart",
  ".pbenum.dart",
  ".pbserver.dart",
  // Go codegen
  ".pb.go",
  ".pb.gw.go",
  ".twirp.go",
  ".gen.go",
  ".generated.go",
  "_gen.go",
  "_generated.go",
  "_string.go",
  // Rust codegen
  ".generated.rs",
  ".pb.rs",
  "_generated.rs",
  // Kotlin / Swift codegen
  ".g.kt",
  ".gen.kt",
  ".generated.kt",
  ".g.swift",
  ".generated.swift",
  // Web sourcemaps
  ".map",
];
const GENERATED_CONTENT_PATTERNS = [
  // Cross-language generator banners used by protoc, sqlc, stringer, bindgen, etc.
  /\bcode generated\b[\s\S]{0,160}\bdo not edit\b/i,
  /\bautomatically generated by\b/i,
  /\bthis file was generated by\b/i,
  // Annotation-style banners commonly used in Java / Kotlin / JS ecosystems.
  /\B@generated\b/i,
  // Named generators across Web, mobile, backend, and protobuf toolchains.
  /\bgenerated by (?:swiftgen|sourcery|protoc|buf|sqlc|openapi(?:-generator)?|openapitools|wire|freezed|build_runner|mockgen|rust-bindgen|apollo|drift|flutterfire|ksp)\b/i,
];

export function isGeneratedArtifactPath(path: string): boolean {
  const normalized = path.replaceAll("\\", "/");
  const segments = normalized.split("/").filter(Boolean);
  if (segments.some((segment) => GENERATED_DIR_SEGMENTS.has(segment))) {
    return true;
  }

  const basename = segments.at(-1) ?? normalized;
  if (GENERATED_FILE_NAMES.has(basename)) return true;
  return GENERATED_FILE_SUFFIXES.some((suffix) => basename.endsWith(suffix));
}

export function hasGeneratedArtifactMarkers(content: string): boolean {
  const header = content.slice(0, 2048).toLowerCase();
  return GENERATED_CONTENT_PATTERNS.some((pattern) => pattern.test(header));
}

export function filterAiRatioEligibleFiles(files: FileEntry[]): FileEntry[] {
  return files.filter((file) => !file.generated && !isGeneratedArtifactPath(file.path));
}

export function countAiRatioEligibleFiles(files: FileEntry[]): { total: number; ai: number } {
  const eligible = filterAiRatioEligibleFiles(files);
  return {
    total: eligible.length,
    ai: eligible.filter((file) => file.by_ai).length,
  };
}

// ─── Functions ───

/**
 * Calculate AI ratio.
 * When line counts are available, uses line-level ratio (added lines only).
 * Falls back to file-count ratio when blob data is unavailable.
 */
export function calcAiRatio(files: FileEntry[], lineCounts?: LineCounts): number {
  if (lineCounts && lineCounts.totalAddedLines > 0) {
    return Math.round((lineCounts.aiAddedLines / lineCounts.totalAddedLines) * 100);
  }
  const eligible = countAiRatioEligibleFiles(files);
  if (eligible.total === 0) return 0;
  return Math.round((eligible.ai / eligible.total) * 100);
}

/** Determine attribution method from available data. */
function resolveMethod(lineCounts?: LineCounts): "line" | "file" | "none" {
  if (!lineCounts) return "file";
  if (lineCounts.totalAddedLines === 0) return "none";
  return "line";
}

/** Build an agentnote entry from collected data. */
export function buildEntry(opts: {
  agent?: string | null;
  sessionId: string;
  model?: string | null;
  interactions: Interaction[];
  commitFiles: string[];
  aiFiles: string[];
  generatedFiles?: string[];
  lineCounts?: LineCounts;
  /** Per-interaction tools, keyed by interaction index. null = no data. */
  interactionTools?: Map<number, string[] | null>;
}): AgentnoteEntry {
  const generatedFiles = new Set(opts.generatedFiles ?? []);
  const files: FileEntry[] = opts.commitFiles.map((path) => ({
    path,
    by_ai: opts.aiFiles.includes(path),
    ...(generatedFiles.has(path) ? { generated: true } : {}),
  }));

  const method = resolveMethod(opts.lineCounts);
  const aiRatio = method === "none" ? 0 : calcAiRatio(files, opts.lineCounts);

  const attribution: Attribution = { ai_ratio: aiRatio, method };
  if (opts.lineCounts) {
    attribution.lines = {
      ai_added: opts.lineCounts.aiAddedLines,
      total_added: opts.lineCounts.totalAddedLines,
      deleted: opts.lineCounts.deletedLines,
    };
  }

  const interactions = opts.interactions.map((i, idx) => {
    const base: Interaction = { prompt: i.prompt, response: i.response };
    if (i.files_touched && i.files_touched.length > 0) {
      base.files_touched = i.files_touched;
    }
    // Attach tools from interactionTools map (preserving null), or inherit from interaction.
    if (opts.interactionTools?.has(idx)) {
      base.tools = opts.interactionTools.get(idx) ?? null;
    } else if (i.tools !== undefined) {
      base.tools = i.tools;
    }
    return base;
  });

  return {
    v: SCHEMA_VERSION,
    agent: opts.agent ?? null,
    session_id: opts.sessionId,
    timestamp: new Date().toISOString(),
    model: opts.model ?? null,
    interactions,
    files,
    attribution,
  };
}
